[project]
name = "project-template"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "numpy==1.26.4",
    "pandas==2.2.1",
    "matplotlib>=3.9.2",
    "seaborn>=0.13.2",
    "jupyter>=1.1.1",
    "ipykernel>=6.29.5",
    "yfinance>=0.2.48",
    "plotly>=5.24.1",
    "ipywidgets>=8.1.5",
    "statsmodels>=0.14.4",
    "pmdarima>=2.0.4",
    "prophet>=1.1.6",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
